---
abstract: 'Unix like streams, but with objects instead of lines of text'
author:
  - 'Johan Lindstrom <johanl@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200001, CPAN::Meta::Converter version 2.110240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Pebble
requires:
  Cache::FileCache: 0
  Cache::NullCache: 0
  Carp: 0
  Chart::Clicker: 0
  Chart::Clicker::Axis::DateTime: 0
  Chart::Clicker::Data::DataSet: 0
  Chart::Clicker::Data::Series: 0
  Class::Autouse: 2.00
  Data::Dumper: 0
  Data::Format::Pretty::Console: 0
  DateTime: 0
  DateTime::Duration: 0
  DateTime::Format::Duration: 0
  DateTimeX::Easy: 0
  Exporter: 0
  File::HomeDir: 0
  File::Slurp: 0
  Format::Human::Bytes: 0
  Getopt::Long: 0
  IO::Pipeline: 0
  JSON::XS: 0
  LWP::UserAgent::WithCache: 0
  List::MoreUtils: 0
  List::Util: 0
  Method::Signatures: 0
  Moose: 0
  MooseX::ClassAttribute: 0
  Pebble::Object::Class: 0
  Statistics::Descriptive: 0
  Text::CSV_XS: 0
  Time::Elapsed: 0
  XML::LibXML: 0
  XML::LibXML::XPathContext: 0
  aliased: 0
version: 0.003
